### ISSUE TITLE
How to get label

### ISSUE THREAD

**Issue by cqf00** [ellson/graphviz#1240]
I want to get the label of a edge.
When I use agnameof , it return null.
What should I do?

Example:
test.gv
`digraph g{
  "node a" -> "node b" [label="edge label"]
}`

c code:
fp = fopen("test.gv", "r");
if (g = agread(fp, 0))
{
	for (v = agfstnode(g); v; v = agnxtnode(g,v))
	{
		for (e = agfstout(g,v); e; e = agnxtout(g,e))
		{
			printf("agtail: %s\n", agnameof(agtail(e)));
			printf("aghead: %s\n", agnameof(aghead(e)));
			printf("edge: %s\n", agnameof(e));
		}
	}
}

Then, the result:
agtail: node a
aghead: node b
edge: (null)

**Comment by emden** [comment]
To get the label of the edge, i.e., the string "edge label", recall that label is an attribute. To get attribute values, use agget():

  char* lbl = agget(e, "label");

lbl will be NULL if no edge has a label attribute, or the edge's label attribute.

Don't confuse an object's name with its label. The confusion can happen because the default label of a node is its name, but this need not be the case. For the graph

graph G {
  label=foo
  abc [label="node label"]
  abc -> def [label="edge label"]
}

agget(x,"label") returns "foo", "node label" and "edge label" for the graph, the node abc and the edge, respectively. If x is the node def, agget(x, "label") returns "".

agnameof(x) returns "G" and "abc" for the graph and the node abc. agnameof(e) for an edge e is NULL unless the edge was created with an ID. 

See http://www.graphviz.org/pdf/Agraph.pdf for more details.
