### ISSUE TITLE
Format svg not recognized

### ISSUE THREAD

**Issue by helperman** [ellson/graphviz#1264]
I use dot.exe to create svg-output file using such a command:
"C:\Program Files (x86)\Graphviz 2.41.20170804.1243\bin\dot.exe" -Tsvg -O -Kdot "C:\graph\inputBeta.graphviz"

Here is what I get:
http://storage5.static.itmages.ru/i/17/0807/h_1502124532_8321547_2103d2d1e8.png

Do you refuse svg-format forever?
Why?

**Comment by emden** [comment]
I'm not sure how the Windows version was built. If it relies on dynamically loaded plug-ins (the usual cased), when dot starts up, it looks for a configuration file to tell it what layout engines and format types are available. To create this file, you can just run dot -c. Running this command is part of the normal installation process for Graphviz.

If dot was built so that all plugins are already linked in, you would need to contact the person building dot and ask that the svg renderer be included.

The svg renderer is part of the core code in Graphviz, so I'm guessing the first case above applies.

**Comment by helperman** [comment]
Thanks!
Now it doesn't give that error!
